version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY="django-insecure-95d_f=yjm%w_r2kuvrs)0f5l1wozcah*z=ssphcg$8q!1mc18-"